import {
  generateDefaultSchema,
  type SchemaContextType,
} from "../client/routes/components/SchemaProvider";
import { TENANTS } from "../constants/tenants";
import { MC_TEST_RESOURCE_SERVICES } from "./mcResourceServicesFixture";

/** Attach the MC services snapshot to a test resource (mirrors the tenant schema). */
const withMcServices = <T extends { resourceId: string }>(resource: T) => ({
  ...resource,
  services: MC_TEST_RESOURCE_SERVICES[resource.resourceId] ?? {},
});

const baseMediaCommonsSchema: SchemaContextType = {
  ...generateDefaultSchema(TENANTS.MC),
  tenant: {
    ...generateDefaultSchema(TENANTS.MC).tenant,
    name: "Media Commons",
    logo: "/mediaCommonsLogo.svg",
    nameForPolicy: "370J Media Commons",
  },
  policy: "<p>Mock policy content for automated tests.</p>",
  mappings: {
    program: {
      "ITP / IMA / Low Res": ["ITP"],
      "General Department": ["GENERAL"],
    },
    role: {
      Student: ["STUDENT"],
      Faculty: ["FACULTY"],
      Staff: ["STAFF"],
    },
    school: {
      "Tisch School of the Arts": ["TISCH"],
      "Tandon School of Engineering": ["TANDON"],
    },
  },
  roles: ["Student", "Faculty", "Staff"],
  form: {
    showBookingType: true,
    showNNumber: true,
    showSponsor: true,
    services: {
      showCatering: true,
      showEquipment: true,
      showSecurity: true,
      showSetup: true,
      showStaffing: true,
    },
  },
  attestations: [
    { id: "checklist", html: "<p>Mock checklist agreement.</p>" },
    { id: "resetRoom", html: "<p>Reset room agreement.</p>" },
    { id: "bookingPolicy", html: "<p>Booking policy agreement.</p>" },
  ],
  calendarConfig: {
    startHour: {
      student: "09:00:00",
      faculty: "09:00:00",
      admin: "06:00:00",
      studentWalkIn: "09:00:00",
      facultyWalkIn: "09:00:00",
      adminWalkIn: "06:00:00",
      studentVIP: "06:00:00",
      facultyVIP: "06:00:00",
      adminVIP: "06:00:00",
    },
    slotUnit: {
      student: 15,
      faculty: 15,
      admin: 15,
      studentWalkIn: 15,
      facultyWalkIn: 15,
      adminWalkIn: 15,
      studentVIP: 15,
      facultyVIP: 15,
      adminVIP: 15,
    },
    multipleResourceSelect: false,
    timeSensitiveRequestWarning: {
      hours: 48,
      isActive: false,
      message: "",
      policyLink: "",
    },
  },
  resources: [
    withMcServices({
      capacity: 30,
      name: "Lecture Hall 202",
      resourceId: "202",
      isEquipment: false,
      calendarId: "mock-calendar-202",
      training: { required: false, formId: "", infoUrl: "" },
      isWalkIn: false,
      isWalkInCanBookTwo: false,
      services: ["equipment", "catering", "cleaning", "security", "setup"],
      minHour: {
        student: 1,
        faculty: 1,
        admin: 1,
        studentWalkIn: 1,
        facultyWalkIn: 1,
        adminWalkIn: 1,
        studentVIP: 1,
        facultyVIP: 1,
        adminVIP: 1,
      },
      maxHour: {
        student: 4,
        faculty: 8,
        admin: 12,
        studentWalkIn: 4,
        facultyWalkIn: 8,
        adminWalkIn: 12,
        studentVIP: 8,
        facultyVIP: 12,
        adminVIP: 16,
      },
    } as any),
    withMcServices({
      capacity: 20,
      name: "Studio 220",
      resourceId: "220",
      isEquipment: false,
      calendarId: "mock-calendar-220",
      training: { required: false, formId: "", infoUrl: "" },
      isWalkIn: true,
      isWalkInCanBookTwo: false,
      services: ["equipment", "staffing"],
      minHour: {
        student: 1,
        faculty: 1,
        admin: 1,
        studentWalkIn: 1,
        facultyWalkIn: 1,
        adminWalkIn: 1,
        studentVIP: 1,
        facultyVIP: 1,
        adminVIP: 1,
      },
      maxHour: {
        student: 3,
        faculty: 6,
        admin: 10,
        studentWalkIn: 3,
        facultyWalkIn: 6,
        adminWalkIn: 10,
        studentVIP: 6,
        facultyVIP: 10,
        adminVIP: 14,
      },
    } as any),
    withMcServices({
      capacity: 15,
      name: "Training Room 230",
      resourceId: "230",
      isEquipment: false,
      calendarId: "mock-calendar-230",
      training: { required: true, formId: "https://docs.google.com/forms/d/e/mock/viewform", infoUrl: "" },
      isWalkIn: false,
      isWalkInCanBookTwo: false,
      services: ["equipment", "catering", "cleaning", "security"],
      minHour: {
        student: 1,
        faculty: 1,
        admin: 1,
        studentWalkIn: 1,
        facultyWalkIn: 1,
        adminWalkIn: 1,
        studentVIP: 1,
        facultyVIP: 1,
        adminVIP: 1,
      },
      maxHour: {
        student: 4,
        faculty: 8,
        admin: 12,
        studentWalkIn: 4,
        facultyWalkIn: 8,
        adminWalkIn: 12,
        studentVIP: 8,
        facultyVIP: 12,
        adminVIP: 16,
      },
    } as any),
  ],
  origins: {
    VIP: true,
    walkIn: true,
  },
  resourceName: "Room(s)",
  emailNotifications: {
    requestedUser: "Your booking request has been received.",
    requestedNeedsApproval: "A booking requires your approval.",
    reviewedNeedsApproval: "A booking requires second approval.",
    approvedWalkIn: "Your walk-in booking has been confirmed.",
    approvedVIP: "Your VIP booking has been confirmed.",
    checkedOut: "You have successfully checked out.",
    checkedIn: "You have successfully checked in.",
    declined: "Your booking request has been declined.",
    canceled: "Your booking has been canceled.",
    canceledLate: "Your booking has been canceled late.",
    noShow: "You have been marked as no-show.",
    closed: "Your booking has been closed.",
    approvedUser: "Your booking has been approved.",
  },
};

const schemaByTenant: Record<string, SchemaContextType> = {
  [TENANTS.MC]: baseMediaCommonsSchema,
  [TENANTS.MEDIA_COMMONS]: {
    ...baseMediaCommonsSchema,
    tenantId: TENANTS.MEDIA_COMMONS,
  },
};

export const getTestTenantSchema = (tenant: string): SchemaContextType | null =>
  schemaByTenant[tenant] ?? null;
